# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - movement-microservice-ecalderc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ef7a0dfbff644ec496ef61bb8913951a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_01e35addff9342e68a268f31c0d39a50 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ef7a0dfbff644ec496ef61bb8913951a }}/movement-microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'movement-microservice-ecalderc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ef1eb5bdd46d416db50052f1a6a54e30 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ef7a0dfbff644ec496ef61bb8913951a }}/movement-microservice:${{ github.sha }}'